facebook :
    client :
        clientId : 610379352727770
        clientSecret: 60cde1daee2a79bc11d2b425d05105e8
        accessTokenUri: https://graph.facebook.com/oauth/access_token
        userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
        scope: email
    resource:
        userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link

google :
    client :
        clientId : 285066490304-iaieeasdavlorjomui57iklfr68k8atj.apps.googleusercontent.com
        clientSecret: ZXnzAjz41kGvJeX-GQ4Jmokm
        accessTokenUri: https://accounts.google.com/o/oauth2/token
        userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
        scope: email, profile
    resource:
        userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo

kakao :
    client :
        clientId :
        accessTokenUri: https://kauth.kakao.com/oauth/token
        userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
    resource:
        userInfoUri: https://kapi.kakao.com/v1/user/me
