spring:
  h2:
    console:
      enabled: true

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:jpashop
    driver-class-name: org.h2.Driver
    hikari.jdbc-url: jdbc:h2:mem:support

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql:
          BasicBinder: TRACE
